export type associateFormInputs = {
  nome: string,
  estadoCivil: string,
  profissao: string,
  nomePai: string,
  nomeMae: string,
  municipio: string,
  estado: string,
  nacionalidade: string,
  dataNascimento: string,
  rua: string,
  numero: number,
  complemento: string,
  bairro: string,
  cep: string,
  localTrabalho: string,
  numeroCarteiraTrabalho: string,
  serieCarteiraTrabalho: string,
  sabeLer: boolean,
  eleitor: boolean,
  carteiraSindical: string,
  cpf: string,
  celular: string,
  filhosMenores: number,
  filhosHomens: number,
  filhosMulheres: number,
  outrosDependentes: number,
};
